# Generated by Django 4.2.14 on 2024-07-29 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersetting',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='usersetting',
            name='filter_exchange',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='usersetting',
            name='filter_sector',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='usersetting',
            name='filter_type',
            field=models.CharField(blank=True, default='both', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='usersetting',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
