# Generated by Django 4.2.14 on 2024-08-01 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeSymbols',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10, unique=True)),
                ('type', models.CharField(max_length=10)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('exchange', models.CharField(blank=True, max_length=50, null=True)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('sector', models.CharField(blank=True, max_length=100, null=True)),
                ('industry', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='usersetting',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='usersetting',
            name='filter_exchange',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='usersetting',
            name='filter_sector',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='usersetting',
            name='filter_symbol',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersetting',
            name='filter_type',
            field=models.CharField(blank=True, default='both', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='usersetting',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
