# Generated by Django 4.2.14 on 2024-08-06 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_tradesymbols_usersetting_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersetting',
            name='filter_exchange',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
