# Generated by Django 4.2.14 on 2024-09-02 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_usersetting_filter_exchange_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersetting',
            name='bot_active',
            field=models.BooleanField(default=True),
        ),
    ]
