# Generated by Django 4.2.14 on 2024-09-02 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_usersetting_bot_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersetting',
            name='bot_active',
            field=models.BooleanField(default=False),
        ),
    ]
