# Generated by Django 4.2.14 on 2024-09-02 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_usersetting_bot_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='botoperation',
            old_name='operation_type',
            new_name='stage',
        ),
        migrations.RemoveField(
            model_name='botoperation',
            name='details',
        ),
        migrations.AddField(
            model_name='botoperation',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='botoperation',
            name='status',
            field=models.CharField(default='Pending', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='botoperation',
            name='stock_symbol',
            field=models.CharField(default='Pending', max_length=10),
            preserve_default=False,
        ),
    ]
