# Generated by Django 4.2.14 on 2024-09-04 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_rename_operation_type_botoperation_stage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersetting',
            name='filter_exchange',
        ),
        migrations.RemoveField(
            model_name='usersetting',
            name='filter_type',
        ),
    ]
